### ISSUE TITLE
Add JohnAlbin to collaborators on https://www.npmjs.com/package/grunt-kss

### ISSUE THREAD

**Issue by JohnAlbin** [kss-node/grunt-kss#1]
Hi @galindus,

We are trying to revive the grunt-kss project. I noticed on https://www.npmjs.com/package/grunt-kss that you are a collaborator.

Can you add me as a collaborator so I can publish new releases of this project?

```sh
npm owner add johnalbin grunt-kss
```

Thanks!

**Comment by galindus** [comment]
Sure. All yours. I only added a version while we migrate to another solution in all our projects.

\BR

**Comment by JohnAlbin** [comment]
Thanks, @galindus! You rock!
