### ISSUE TITLE
Styleguide is generated but the process does not terminate

### ISSUE THREAD

**Issue by adamkudrna** [kss-node/grunt-kss#10]
I am migrating my project [Bootstrap UI](http://www.bootstrap-ui.com) from grunt-styleguide which is no longer maintained to grunt-kss. Everything works fine except the styleguide generation process never terminates. Everytime I run `grunt kss` the styleguide is generated successfully but the process in console does not terminate and must be cancelled manually (`CTRL + C`).

Of course I have suspected my environment first but it looks like it's in something else, the same thing is happening also on Travis.

- PR in the Bootstrap UI project: https://github.com/visionappscz/bootstrap-ui/pull/67
- Travis build log: https://travis-ci.org/visionappscz/bootstrap-ui/builds/128987614

My environment:
- tested on Node v5.5.0, v5.11.1 and v6.0.0
- grunt-kss v5.0.0
- grunt v1.0.1
- Mac OS X 10.11.4

Could you please have a look at this?

**Comment by martijndewit** [comment]
got the same issue over here. Its prevents me to use kss as in a grunt watch or use it with other tasks... All tasks after the kss task aren't ran because of that.

**Comment by adamkudrna** [comment]
@martijndewit Feel free to use our fork of grunt-kss until we polish the PR #14 to fix the upstream: https://github.com/visionappscz/grunt-kss

**Comment by martijndewit** [comment]
@adamkudrna Ahhh ok, didn't notice the relation :).  Now using the forked branch and its working like sunshine! Only figure out how to get your forked version in the package.json... ( if thats a good idea...)

**Comment by adamkudrna** [comment]
Just like this:

```
  "devDependencies": {
    …
    "grunt-kss": "visionappscz/grunt-kss#master",
    …
  },
```
