### ISSUE TITLE
Re-publish v0.2.6 on npm registry

### ISSUE THREAD

**Issue by dverbru** [kss-node/grunt-kss#18]
The release history in your README mentions v0.2.6 (which is precisely the version one of my projects depend on) but it is not available for download anymore, instead there is v0.2.8. Is that the same version?

**Comment by JohnAlbin** [comment]
Yeah, the previous maintainer unpublished all the old versions. I've recreated the git tags for some of those versions. But it's not possible to republish the old versions, afaik.
